/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.validation

import org.eclipse.xtext.validation.Check
import org.xtext.example.ansic.type_specifier
import org.xtext.example.ansic.AnsicPackage
/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class AnsicValidator extends AbstractAnsicValidator {
	
  public static val INVALID_NAME = 'invalidName'

  	@Check
	def checkGreetingStartsWithCapital(type_specifier tName) {
		println(tName.type_name_str);
		if(tName.type_name_str.equals("char")){
			error("Não pode char, cuzão!", AnsicPackage.Literals.TYPE_SPECIFIER__TYPE_NAME_STR);
		}
	}
	
  
  //
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					AnsicPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
