/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.ansic.ui.internal.AnsicActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AnsicExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AnsicActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AnsicActivator.getInstance().getInjector(AnsicActivator.ORG_XTEXT_EXAMPLE_ANSIC);
	}
	
}
