/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.ansic.ui.internal.AnsicActivator;

public class AnsicUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AnsicActivator.getInstance().getInjector("org.xtext.example.Ansic");
	}

}
