/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>argument expression list</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.argument_expression_list#getAssignment_expressions <em>Assignment expressions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ansic.AnsicPackage#getargument_expression_list()
 * @model
 * @generated
 */
public interface argument_expression_list extends EObject
{
  /**
   * Returns the value of the '<em><b>Assignment expressions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.ansic.assignment_expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assignment expressions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignment expressions</em>' containment reference list.
   * @see org.xtext.example.ansic.AnsicPackage#getargument_expression_list_Assignment_expressions()
   * @model containment="true"
   * @generated
   */
  EList<assignment_expression> getAssignment_expressions();

} // argument_expression_list
