/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Block Item List Linha Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.BlockItemListLinhaAction#getBlock_item <em>Block item</em>}</li>
 *   <li>{@link org.xtext.example.ansic.BlockItemListLinhaAction#getBlock_item_list_linha <em>Block item list linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ansic.AnsicPackage#getBlockItemListLinhaAction()
 * @model
 * @generated
 */
public interface BlockItemListLinhaAction extends block_item_list_linha
{
  /**
   * Returns the value of the '<em><b>Block item</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Block item</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block item</em>' containment reference.
   * @see #setBlock_item(block_item)
   * @see org.xtext.example.ansic.AnsicPackage#getBlockItemListLinhaAction_Block_item()
   * @model containment="true"
   * @generated
   */
  block_item getBlock_item();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.BlockItemListLinhaAction#getBlock_item <em>Block item</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block item</em>' containment reference.
   * @see #getBlock_item()
   * @generated
   */
  void setBlock_item(block_item value);

  /**
   * Returns the value of the '<em><b>Block item list linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Block item list linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block item list linha</em>' containment reference.
   * @see #setBlock_item_list_linha(block_item_list_linha)
   * @see org.xtext.example.ansic.AnsicPackage#getBlockItemListLinhaAction_Block_item_list_linha()
   * @model containment="true"
   * @generated
   */
  block_item_list_linha getBlock_item_list_linha();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.BlockItemListLinhaAction#getBlock_item_list_linha <em>Block item list linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block item list linha</em>' containment reference.
   * @see #getBlock_item_list_linha()
   * @generated
   */
  void setBlock_item_list_linha(block_item_list_linha value);

} // BlockItemListLinhaAction
