/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>compound statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.compound_statement#getBlock_item_list <em>Block item list</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ansic.AnsicPackage#getcompound_statement()
 * @model
 * @generated
 */
public interface compound_statement extends statement
{
  /**
   * Returns the value of the '<em><b>Block item list</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Block item list</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block item list</em>' containment reference.
   * @see #setBlock_item_list(block_item_list)
   * @see org.xtext.example.ansic.AnsicPackage#getcompound_statement_Block_item_list()
   * @model containment="true"
   * @generated
   */
  block_item_list getBlock_item_list();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.compound_statement#getBlock_item_list <em>Block item list</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block item list</em>' containment reference.
   * @see #getBlock_item_list()
   * @generated
   */
  void setBlock_item_list(block_item_list value);

} // compound_statement
