/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>designator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.designator#getConstant_expression <em>Constant expression</em>}</li>
 *   <li>{@link org.xtext.example.ansic.designator#getIdentifier <em>Identifier</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ansic.AnsicPackage#getdesignator()
 * @model
 * @generated
 */
public interface designator extends EObject
{
  /**
   * Returns the value of the '<em><b>Constant expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constant expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant expression</em>' containment reference.
   * @see #setConstant_expression(conditional_expression)
   * @see org.xtext.example.ansic.AnsicPackage#getdesignator_Constant_expression()
   * @model containment="true"
   * @generated
   */
  conditional_expression getConstant_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.designator#getConstant_expression <em>Constant expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant expression</em>' containment reference.
   * @see #getConstant_expression()
   * @generated
   */
  void setConstant_expression(conditional_expression value);

  /**
   * Returns the value of the '<em><b>Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Identifier</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier</em>' attribute.
   * @see #setIdentifier(String)
   * @see org.xtext.example.ansic.AnsicPackage#getdesignator_Identifier()
   * @model
   * @generated
   */
  String getIdentifier();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.designator#getIdentifier <em>Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier</em>' attribute.
   * @see #getIdentifier()
   * @generated
   */
  void setIdentifier(String value);

} // designator
