/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>equality expression complement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.equality_expression_complement#getRelational_expression <em>Relational expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ansic.AnsicPackage#getequality_expression_complement()
 * @model
 * @generated
 */
public interface equality_expression_complement extends EObject
{
  /**
   * Returns the value of the '<em><b>Relational expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relational expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relational expression</em>' containment reference.
   * @see #setRelational_expression(relational_expression)
   * @see org.xtext.example.ansic.AnsicPackage#getequality_expression_complement_Relational_expression()
   * @model containment="true"
   * @generated
   */
  relational_expression getRelational_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.equality_expression_complement#getRelational_expression <em>Relational expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relational expression</em>' containment reference.
   * @see #getRelational_expression()
   * @generated
   */
  void setRelational_expression(relational_expression value);

} // equality_expression_complement
