/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Linha Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.ExpressionLinhaAction#getAssignment_expression <em>Assignment expression</em>}</li>
 *   <li>{@link org.xtext.example.ansic.ExpressionLinhaAction#getExpression_linha <em>Expression linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ansic.AnsicPackage#getExpressionLinhaAction()
 * @model
 * @generated
 */
public interface ExpressionLinhaAction extends expression_linha
{
  /**
   * Returns the value of the '<em><b>Assignment expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assignment expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignment expression</em>' containment reference.
   * @see #setAssignment_expression(assignment_expression)
   * @see org.xtext.example.ansic.AnsicPackage#getExpressionLinhaAction_Assignment_expression()
   * @model containment="true"
   * @generated
   */
  assignment_expression getAssignment_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.ExpressionLinhaAction#getAssignment_expression <em>Assignment expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assignment expression</em>' containment reference.
   * @see #getAssignment_expression()
   * @generated
   */
  void setAssignment_expression(assignment_expression value);

  /**
   * Returns the value of the '<em><b>Expression linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression linha</em>' containment reference.
   * @see #setExpression_linha(expression_linha)
   * @see org.xtext.example.ansic.AnsicPackage#getExpressionLinhaAction_Expression_linha()
   * @model containment="true"
   * @generated
   */
  expression_linha getExpression_linha();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.ExpressionLinhaAction#getExpression_linha <em>Expression linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression linha</em>' containment reference.
   * @see #getExpression_linha()
   * @generated
   */
  void setExpression_linha(expression_linha value);

} // ExpressionLinhaAction
