/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiplicative Expression Linha Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.MultiplicativeExpressionLinhaAction#getMultiplicative_expression_complement <em>Multiplicative expression complement</em>}</li>
 *   <li>{@link org.xtext.example.ansic.MultiplicativeExpressionLinhaAction#getMultiplicative_expression_linha <em>Multiplicative expression linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ansic.AnsicPackage#getMultiplicativeExpressionLinhaAction()
 * @model
 * @generated
 */
public interface MultiplicativeExpressionLinhaAction extends multiplicative_expression_linha
{
  /**
   * Returns the value of the '<em><b>Multiplicative expression complement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Multiplicative expression complement</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multiplicative expression complement</em>' containment reference.
   * @see #setMultiplicative_expression_complement(multiplicative_expression_complement)
   * @see org.xtext.example.ansic.AnsicPackage#getMultiplicativeExpressionLinhaAction_Multiplicative_expression_complement()
   * @model containment="true"
   * @generated
   */
  multiplicative_expression_complement getMultiplicative_expression_complement();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.MultiplicativeExpressionLinhaAction#getMultiplicative_expression_complement <em>Multiplicative expression complement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Multiplicative expression complement</em>' containment reference.
   * @see #getMultiplicative_expression_complement()
   * @generated
   */
  void setMultiplicative_expression_complement(multiplicative_expression_complement value);

  /**
   * Returns the value of the '<em><b>Multiplicative expression linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Multiplicative expression linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multiplicative expression linha</em>' containment reference.
   * @see #setMultiplicative_expression_linha(multiplicative_expression_linha)
   * @see org.xtext.example.ansic.AnsicPackage#getMultiplicativeExpressionLinhaAction_Multiplicative_expression_linha()
   * @model containment="true"
   * @generated
   */
  multiplicative_expression_linha getMultiplicative_expression_linha();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.MultiplicativeExpressionLinhaAction#getMultiplicative_expression_linha <em>Multiplicative expression linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Multiplicative expression linha</em>' containment reference.
   * @see #getMultiplicative_expression_linha()
   * @generated
   */
  void setMultiplicative_expression_linha(multiplicative_expression_linha value);

} // MultiplicativeExpressionLinhaAction
