/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>parameter type list</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.parameter_type_list#getParameter_list <em>Parameter list</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ansic.AnsicPackage#getparameter_type_list()
 * @model
 * @generated
 */
public interface parameter_type_list extends EObject
{
  /**
   * Returns the value of the '<em><b>Parameter list</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.ansic.parameter_list}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter list</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter list</em>' containment reference list.
   * @see org.xtext.example.ansic.AnsicPackage#getparameter_type_list_Parameter_list()
   * @model containment="true"
   * @generated
   */
  EList<parameter_list> getParameter_list();

} // parameter_type_list
