/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>parameter list</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.parameter_list#getParameter_declaration <em>Parameter declaration</em>}</li>
 *   <li>{@link org.xtext.example.ansic.parameter_list#getParameter_list_linha <em>Parameter list linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ansic.AnsicPackage#getparameter_list()
 * @model
 * @generated
 */
public interface parameter_list extends EObject
{
  /**
   * Returns the value of the '<em><b>Parameter declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter declaration</em>' containment reference.
   * @see #setParameter_declaration(parameter_declaration)
   * @see org.xtext.example.ansic.AnsicPackage#getparameter_list_Parameter_declaration()
   * @model containment="true"
   * @generated
   */
  parameter_declaration getParameter_declaration();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.parameter_list#getParameter_declaration <em>Parameter declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter declaration</em>' containment reference.
   * @see #getParameter_declaration()
   * @generated
   */
  void setParameter_declaration(parameter_declaration value);

  /**
   * Returns the value of the '<em><b>Parameter list linha</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.ansic.parameter_list_linha}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter list linha</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter list linha</em>' containment reference list.
   * @see org.xtext.example.ansic.AnsicPackage#getparameter_list_Parameter_list_linha()
   * @model containment="true"
   * @generated
   */
  EList<parameter_list_linha> getParameter_list_linha();

} // parameter_list
