/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>parameter list linha</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.ansic.AnsicPackage#getparameter_list_linha()
 * @model
 * @generated
 */
public interface parameter_list_linha extends EObject
{
} // parameter_list_linha
