/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter List Linha Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.ParameterListLinhaAction#getParameter_declaration <em>Parameter declaration</em>}</li>
 *   <li>{@link org.xtext.example.ansic.ParameterListLinhaAction#getParameter_list_linha <em>Parameter list linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ansic.AnsicPackage#getParameterListLinhaAction()
 * @model
 * @generated
 */
public interface ParameterListLinhaAction extends parameter_list_linha
{
  /**
   * Returns the value of the '<em><b>Parameter declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter declaration</em>' containment reference.
   * @see #setParameter_declaration(parameter_declaration)
   * @see org.xtext.example.ansic.AnsicPackage#getParameterListLinhaAction_Parameter_declaration()
   * @model containment="true"
   * @generated
   */
  parameter_declaration getParameter_declaration();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.ParameterListLinhaAction#getParameter_declaration <em>Parameter declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter declaration</em>' containment reference.
   * @see #getParameter_declaration()
   * @generated
   */
  void setParameter_declaration(parameter_declaration value);

  /**
   * Returns the value of the '<em><b>Parameter list linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter list linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter list linha</em>' containment reference.
   * @see #setParameter_list_linha(parameter_list_linha)
   * @see org.xtext.example.ansic.AnsicPackage#getParameterListLinhaAction_Parameter_list_linha()
   * @model containment="true"
   * @generated
   */
  parameter_list_linha getParameter_list_linha();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.ParameterListLinhaAction#getParameter_list_linha <em>Parameter list linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter list linha</em>' containment reference.
   * @see #getParameter_list_linha()
   * @generated
   */
  void setParameter_list_linha(parameter_list_linha value);

} // ParameterListLinhaAction
