/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Postfix Expression Complement Empty</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.ansic.AnsicPackage#getPostfixExpressionComplementEmpty()
 * @model
 * @generated
 */
public interface PostfixExpressionComplementEmpty extends postfix_expression_complement
{
} // PostfixExpressionComplementEmpty
