/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Postfix Expression Complement Arg List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.PostfixExpressionComplementArgList#getArgument_expression_list <em>Argument expression list</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ansic.AnsicPackage#getPostfixExpressionComplementArgList()
 * @model
 * @generated
 */
public interface PostfixExpressionComplementArgList extends postfix_expression_complement
{
  /**
   * Returns the value of the '<em><b>Argument expression list</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.ansic.argument_expression_list}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Argument expression list</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument expression list</em>' containment reference list.
   * @see org.xtext.example.ansic.AnsicPackage#getPostfixExpressionComplementArgList_Argument_expression_list()
   * @model containment="true"
   * @generated
   */
  EList<argument_expression_list> getArgument_expression_list();

} // PostfixExpressionComplementArgList
