/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>postfix expression complement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.ansic.AnsicPackage#getpostfix_expression_complement()
 * @model
 * @generated
 */
public interface postfix_expression_complement extends EObject
{
} // postfix_expression_complement
