/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>relational expression linha</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.relational_expression_linha#getRelational_expression_complement <em>Relational expression complement</em>}</li>
 *   <li>{@link org.xtext.example.ansic.relational_expression_linha#getRelational_expression_linha <em>Relational expression linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ansic.AnsicPackage#getrelational_expression_linha()
 * @model
 * @generated
 */
public interface relational_expression_linha extends EObject
{
  /**
   * Returns the value of the '<em><b>Relational expression complement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relational expression complement</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relational expression complement</em>' containment reference.
   * @see #setRelational_expression_complement(relational_expression_complement)
   * @see org.xtext.example.ansic.AnsicPackage#getrelational_expression_linha_Relational_expression_complement()
   * @model containment="true"
   * @generated
   */
  relational_expression_complement getRelational_expression_complement();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.relational_expression_linha#getRelational_expression_complement <em>Relational expression complement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relational expression complement</em>' containment reference.
   * @see #getRelational_expression_complement()
   * @generated
   */
  void setRelational_expression_complement(relational_expression_complement value);

  /**
   * Returns the value of the '<em><b>Relational expression linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relational expression linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relational expression linha</em>' containment reference.
   * @see #setRelational_expression_linha(relational_expression_linha)
   * @see org.xtext.example.ansic.AnsicPackage#getrelational_expression_linha_Relational_expression_linha()
   * @model containment="true"
   * @generated
   */
  relational_expression_linha getRelational_expression_linha();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.relational_expression_linha#getRelational_expression_linha <em>Relational expression linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relational expression linha</em>' containment reference.
   * @see #getRelational_expression_linha()
   * @generated
   */
  void setRelational_expression_linha(relational_expression_linha value);

} // relational_expression_linha
