/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>struct or union specifier complement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.ansic.AnsicPackage#getstruct_or_union_specifier_complement()
 * @model
 * @generated
 */
public interface struct_or_union_specifier_complement extends EObject
{
} // struct_or_union_specifier_complement
