/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>translation unit linha</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.ansic.AnsicPackage#gettranslation_unit_linha()
 * @model
 * @generated
 */
public interface translation_unit_linha extends EObject
{
} // translation_unit_linha
