/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>type qualifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.type_qualifier#getNamez <em>Namez</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ansic.AnsicPackage#gettype_qualifier()
 * @model
 * @generated
 */
public interface type_qualifier extends EObject
{
  /**
   * Returns the value of the '<em><b>Namez</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Namez</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Namez</em>' attribute.
   * @see #setNamez(String)
   * @see org.xtext.example.ansic.AnsicPackage#gettype_qualifier_Namez()
   * @model
   * @generated
   */
  String getNamez();

  /**
   * Sets the value of the '{@link org.xtext.example.ansic.type_qualifier#getNamez <em>Namez</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Namez</em>' attribute.
   * @see #getNamez()
   * @generated
   */
  void setNamez(String value);

} // type_qualifier
