/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example;

import org.xtext.example.AnsicStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AnsicStandaloneSetup extends AnsicStandaloneSetupGenerated {
  public static void doSetup() {
    AnsicStandaloneSetup _ansicStandaloneSetup = new AnsicStandaloneSetup();
    _ansicStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
