/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example;

import org.xtext.example.AbstractAnsicRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AnsicRuntimeModule extends AbstractAnsicRuntimeModule {
}
