/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.block_item_list;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>block item list</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class block_item_listImpl extends MinimalEObjectImpl.Container implements block_item_list
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected block_item_listImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.BLOCK_ITEM_LIST;
  }

} //block_item_listImpl
