/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.block_item_list;
import org.xtext.example.ansic.compound_statement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>compound statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.impl.compound_statementImpl#getBlock_item_list <em>Block item list</em>}</li>
 * </ul>
 *
 * @generated
 */
public class compound_statementImpl extends statementImpl implements compound_statement
{
  /**
   * The cached value of the '{@link #getBlock_item_list() <em>Block item list</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBlock_item_list()
   * @generated
   * @ordered
   */
  protected block_item_list block_item_list;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected compound_statementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.COMPOUND_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public block_item_list getBlock_item_list()
  {
    return block_item_list;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBlock_item_list(block_item_list newBlock_item_list, NotificationChain msgs)
  {
    block_item_list oldBlock_item_list = block_item_list;
    block_item_list = newBlock_item_list;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsicPackage.COMPOUND_STATEMENT__BLOCK_ITEM_LIST, oldBlock_item_list, newBlock_item_list);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBlock_item_list(block_item_list newBlock_item_list)
  {
    if (newBlock_item_list != block_item_list)
    {
      NotificationChain msgs = null;
      if (block_item_list != null)
        msgs = ((InternalEObject)block_item_list).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.COMPOUND_STATEMENT__BLOCK_ITEM_LIST, null, msgs);
      if (newBlock_item_list != null)
        msgs = ((InternalEObject)newBlock_item_list).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.COMPOUND_STATEMENT__BLOCK_ITEM_LIST, null, msgs);
      msgs = basicSetBlock_item_list(newBlock_item_list, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.COMPOUND_STATEMENT__BLOCK_ITEM_LIST, newBlock_item_list, newBlock_item_list));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AnsicPackage.COMPOUND_STATEMENT__BLOCK_ITEM_LIST:
        return basicSetBlock_item_list(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AnsicPackage.COMPOUND_STATEMENT__BLOCK_ITEM_LIST:
        return getBlock_item_list();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AnsicPackage.COMPOUND_STATEMENT__BLOCK_ITEM_LIST:
        setBlock_item_list((block_item_list)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.COMPOUND_STATEMENT__BLOCK_ITEM_LIST:
        setBlock_item_list((block_item_list)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.COMPOUND_STATEMENT__BLOCK_ITEM_LIST:
        return block_item_list != null;
    }
    return super.eIsSet(featureID);
  }

} //compound_statementImpl
