/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.declarator;
import org.xtext.example.ansic.direct_declarator;
import org.xtext.example.ansic.direct_declarator_linha;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>direct declarator</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.impl.direct_declaratorImpl#getIdentifier <em>Identifier</em>}</li>
 *   <li>{@link org.xtext.example.ansic.impl.direct_declaratorImpl#getDirect_declarator_linha <em>Direct declarator linha</em>}</li>
 *   <li>{@link org.xtext.example.ansic.impl.direct_declaratorImpl#getDeclarator <em>Declarator</em>}</li>
 * </ul>
 *
 * @generated
 */
public class direct_declaratorImpl extends MinimalEObjectImpl.Container implements direct_declarator
{
  /**
   * The default value of the '{@link #getIdentifier() <em>Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdentifier()
   * @generated
   * @ordered
   */
  protected static final String IDENTIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIdentifier() <em>Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdentifier()
   * @generated
   * @ordered
   */
  protected String identifier = IDENTIFIER_EDEFAULT;

  /**
   * The cached value of the '{@link #getDirect_declarator_linha() <em>Direct declarator linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirect_declarator_linha()
   * @generated
   * @ordered
   */
  protected direct_declarator_linha direct_declarator_linha;

  /**
   * The cached value of the '{@link #getDeclarator() <em>Declarator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclarator()
   * @generated
   * @ordered
   */
  protected declarator declarator;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected direct_declaratorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.DIRECT_DECLARATOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIdentifier()
  {
    return identifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIdentifier(String newIdentifier)
  {
    String oldIdentifier = identifier;
    identifier = newIdentifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.DIRECT_DECLARATOR__IDENTIFIER, oldIdentifier, identifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public direct_declarator_linha getDirect_declarator_linha()
  {
    return direct_declarator_linha;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDirect_declarator_linha(direct_declarator_linha newDirect_declarator_linha, NotificationChain msgs)
  {
    direct_declarator_linha oldDirect_declarator_linha = direct_declarator_linha;
    direct_declarator_linha = newDirect_declarator_linha;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsicPackage.DIRECT_DECLARATOR__DIRECT_DECLARATOR_LINHA, oldDirect_declarator_linha, newDirect_declarator_linha);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDirect_declarator_linha(direct_declarator_linha newDirect_declarator_linha)
  {
    if (newDirect_declarator_linha != direct_declarator_linha)
    {
      NotificationChain msgs = null;
      if (direct_declarator_linha != null)
        msgs = ((InternalEObject)direct_declarator_linha).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.DIRECT_DECLARATOR__DIRECT_DECLARATOR_LINHA, null, msgs);
      if (newDirect_declarator_linha != null)
        msgs = ((InternalEObject)newDirect_declarator_linha).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.DIRECT_DECLARATOR__DIRECT_DECLARATOR_LINHA, null, msgs);
      msgs = basicSetDirect_declarator_linha(newDirect_declarator_linha, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.DIRECT_DECLARATOR__DIRECT_DECLARATOR_LINHA, newDirect_declarator_linha, newDirect_declarator_linha));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public declarator getDeclarator()
  {
    return declarator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDeclarator(declarator newDeclarator, NotificationChain msgs)
  {
    declarator oldDeclarator = declarator;
    declarator = newDeclarator;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsicPackage.DIRECT_DECLARATOR__DECLARATOR, oldDeclarator, newDeclarator);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDeclarator(declarator newDeclarator)
  {
    if (newDeclarator != declarator)
    {
      NotificationChain msgs = null;
      if (declarator != null)
        msgs = ((InternalEObject)declarator).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.DIRECT_DECLARATOR__DECLARATOR, null, msgs);
      if (newDeclarator != null)
        msgs = ((InternalEObject)newDeclarator).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.DIRECT_DECLARATOR__DECLARATOR, null, msgs);
      msgs = basicSetDeclarator(newDeclarator, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.DIRECT_DECLARATOR__DECLARATOR, newDeclarator, newDeclarator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AnsicPackage.DIRECT_DECLARATOR__DIRECT_DECLARATOR_LINHA:
        return basicSetDirect_declarator_linha(null, msgs);
      case AnsicPackage.DIRECT_DECLARATOR__DECLARATOR:
        return basicSetDeclarator(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AnsicPackage.DIRECT_DECLARATOR__IDENTIFIER:
        return getIdentifier();
      case AnsicPackage.DIRECT_DECLARATOR__DIRECT_DECLARATOR_LINHA:
        return getDirect_declarator_linha();
      case AnsicPackage.DIRECT_DECLARATOR__DECLARATOR:
        return getDeclarator();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AnsicPackage.DIRECT_DECLARATOR__IDENTIFIER:
        setIdentifier((String)newValue);
        return;
      case AnsicPackage.DIRECT_DECLARATOR__DIRECT_DECLARATOR_LINHA:
        setDirect_declarator_linha((direct_declarator_linha)newValue);
        return;
      case AnsicPackage.DIRECT_DECLARATOR__DECLARATOR:
        setDeclarator((declarator)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.DIRECT_DECLARATOR__IDENTIFIER:
        setIdentifier(IDENTIFIER_EDEFAULT);
        return;
      case AnsicPackage.DIRECT_DECLARATOR__DIRECT_DECLARATOR_LINHA:
        setDirect_declarator_linha((direct_declarator_linha)null);
        return;
      case AnsicPackage.DIRECT_DECLARATOR__DECLARATOR:
        setDeclarator((declarator)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.DIRECT_DECLARATOR__IDENTIFIER:
        return IDENTIFIER_EDEFAULT == null ? identifier != null : !IDENTIFIER_EDEFAULT.equals(identifier);
      case AnsicPackage.DIRECT_DECLARATOR__DIRECT_DECLARATOR_LINHA:
        return direct_declarator_linha != null;
      case AnsicPackage.DIRECT_DECLARATOR__DECLARATOR:
        return declarator != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (identifier: ");
    result.append(identifier);
    result.append(')');
    return result.toString();
  }

} //direct_declaratorImpl
