/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.direct_declarator_linha;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>direct declarator linha</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class direct_declarator_linhaImpl extends MinimalEObjectImpl.Container implements direct_declarator_linha
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected direct_declarator_linhaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.DIRECT_DECLARATOR_LINHA;
  }

} //direct_declarator_linhaImpl
