/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.equality_expression_complement;
import org.xtext.example.ansic.relational_expression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>equality expression complement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.impl.equality_expression_complementImpl#getRelational_expression <em>Relational expression</em>}</li>
 * </ul>
 *
 * @generated
 */
public class equality_expression_complementImpl extends MinimalEObjectImpl.Container implements equality_expression_complement
{
  /**
   * The cached value of the '{@link #getRelational_expression() <em>Relational expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelational_expression()
   * @generated
   * @ordered
   */
  protected relational_expression relational_expression;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected equality_expression_complementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.EQUALITY_EXPRESSION_COMPLEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public relational_expression getRelational_expression()
  {
    return relational_expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRelational_expression(relational_expression newRelational_expression, NotificationChain msgs)
  {
    relational_expression oldRelational_expression = relational_expression;
    relational_expression = newRelational_expression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsicPackage.EQUALITY_EXPRESSION_COMPLEMENT__RELATIONAL_EXPRESSION, oldRelational_expression, newRelational_expression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRelational_expression(relational_expression newRelational_expression)
  {
    if (newRelational_expression != relational_expression)
    {
      NotificationChain msgs = null;
      if (relational_expression != null)
        msgs = ((InternalEObject)relational_expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.EQUALITY_EXPRESSION_COMPLEMENT__RELATIONAL_EXPRESSION, null, msgs);
      if (newRelational_expression != null)
        msgs = ((InternalEObject)newRelational_expression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.EQUALITY_EXPRESSION_COMPLEMENT__RELATIONAL_EXPRESSION, null, msgs);
      msgs = basicSetRelational_expression(newRelational_expression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.EQUALITY_EXPRESSION_COMPLEMENT__RELATIONAL_EXPRESSION, newRelational_expression, newRelational_expression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AnsicPackage.EQUALITY_EXPRESSION_COMPLEMENT__RELATIONAL_EXPRESSION:
        return basicSetRelational_expression(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AnsicPackage.EQUALITY_EXPRESSION_COMPLEMENT__RELATIONAL_EXPRESSION:
        return getRelational_expression();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AnsicPackage.EQUALITY_EXPRESSION_COMPLEMENT__RELATIONAL_EXPRESSION:
        setRelational_expression((relational_expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.EQUALITY_EXPRESSION_COMPLEMENT__RELATIONAL_EXPRESSION:
        setRelational_expression((relational_expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.EQUALITY_EXPRESSION_COMPLEMENT__RELATIONAL_EXPRESSION:
        return relational_expression != null;
    }
    return super.eIsSet(featureID);
  }

} //equality_expression_complementImpl
