/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.EqualityExpressionLinhaAction;
import org.xtext.example.ansic.equality_expression_complement;
import org.xtext.example.ansic.equality_expression_linha;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Equality Expression Linha Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.impl.EqualityExpressionLinhaActionImpl#getEquality_expression_complement <em>Equality expression complement</em>}</li>
 *   <li>{@link org.xtext.example.ansic.impl.EqualityExpressionLinhaActionImpl#getEquality_expression_linha <em>Equality expression linha</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EqualityExpressionLinhaActionImpl extends equality_expression_linhaImpl implements EqualityExpressionLinhaAction
{
  /**
   * The cached value of the '{@link #getEquality_expression_complement() <em>Equality expression complement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEquality_expression_complement()
   * @generated
   * @ordered
   */
  protected equality_expression_complement equality_expression_complement;

  /**
   * The cached value of the '{@link #getEquality_expression_linha() <em>Equality expression linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEquality_expression_linha()
   * @generated
   * @ordered
   */
  protected equality_expression_linha equality_expression_linha;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EqualityExpressionLinhaActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.EQUALITY_EXPRESSION_LINHA_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public equality_expression_complement getEquality_expression_complement()
  {
    return equality_expression_complement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEquality_expression_complement(equality_expression_complement newEquality_expression_complement, NotificationChain msgs)
  {
    equality_expression_complement oldEquality_expression_complement = equality_expression_complement;
    equality_expression_complement = newEquality_expression_complement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_COMPLEMENT, oldEquality_expression_complement, newEquality_expression_complement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEquality_expression_complement(equality_expression_complement newEquality_expression_complement)
  {
    if (newEquality_expression_complement != equality_expression_complement)
    {
      NotificationChain msgs = null;
      if (equality_expression_complement != null)
        msgs = ((InternalEObject)equality_expression_complement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_COMPLEMENT, null, msgs);
      if (newEquality_expression_complement != null)
        msgs = ((InternalEObject)newEquality_expression_complement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_COMPLEMENT, null, msgs);
      msgs = basicSetEquality_expression_complement(newEquality_expression_complement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_COMPLEMENT, newEquality_expression_complement, newEquality_expression_complement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public equality_expression_linha getEquality_expression_linha()
  {
    return equality_expression_linha;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEquality_expression_linha(equality_expression_linha newEquality_expression_linha, NotificationChain msgs)
  {
    equality_expression_linha oldEquality_expression_linha = equality_expression_linha;
    equality_expression_linha = newEquality_expression_linha;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_LINHA, oldEquality_expression_linha, newEquality_expression_linha);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEquality_expression_linha(equality_expression_linha newEquality_expression_linha)
  {
    if (newEquality_expression_linha != equality_expression_linha)
    {
      NotificationChain msgs = null;
      if (equality_expression_linha != null)
        msgs = ((InternalEObject)equality_expression_linha).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_LINHA, null, msgs);
      if (newEquality_expression_linha != null)
        msgs = ((InternalEObject)newEquality_expression_linha).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_LINHA, null, msgs);
      msgs = basicSetEquality_expression_linha(newEquality_expression_linha, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_LINHA, newEquality_expression_linha, newEquality_expression_linha));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_COMPLEMENT:
        return basicSetEquality_expression_complement(null, msgs);
      case AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_LINHA:
        return basicSetEquality_expression_linha(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_COMPLEMENT:
        return getEquality_expression_complement();
      case AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_LINHA:
        return getEquality_expression_linha();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_COMPLEMENT:
        setEquality_expression_complement((equality_expression_complement)newValue);
        return;
      case AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_LINHA:
        setEquality_expression_linha((equality_expression_linha)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_COMPLEMENT:
        setEquality_expression_complement((equality_expression_complement)null);
        return;
      case AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_LINHA:
        setEquality_expression_linha((equality_expression_linha)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_COMPLEMENT:
        return equality_expression_complement != null;
      case AnsicPackage.EQUALITY_EXPRESSION_LINHA_ACTION__EQUALITY_EXPRESSION_LINHA:
        return equality_expression_linha != null;
    }
    return super.eIsSet(featureID);
  }

} //EqualityExpressionLinhaActionImpl
