/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.exclusive_or_expression_linha;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>exclusive or expression linha</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class exclusive_or_expression_linhaImpl extends MinimalEObjectImpl.Container implements exclusive_or_expression_linha
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected exclusive_or_expression_linhaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.EXCLUSIVE_OR_EXPRESSION_LINHA;
  }

} //exclusive_or_expression_linhaImpl
