/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.generic_assoc_list_linha;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>generic assoc list linha</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class generic_assoc_list_linhaImpl extends MinimalEObjectImpl.Container implements generic_assoc_list_linha
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected generic_assoc_list_linhaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.GENERIC_ASSOC_LIST_LINHA;
  }

} //generic_assoc_list_linhaImpl
