/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.parameter_list_linha;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>parameter list linha</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class parameter_list_linhaImpl extends MinimalEObjectImpl.Container implements parameter_list_linha
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected parameter_list_linhaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.PARAMETER_LIST_LINHA;
  }

} //parameter_list_linhaImpl
