/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.PostfixExpressionComplementArgList;
import org.xtext.example.ansic.argument_expression_list;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Postfix Expression Complement Arg List</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.impl.PostfixExpressionComplementArgListImpl#getArgument_expression_list <em>Argument expression list</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PostfixExpressionComplementArgListImpl extends postfix_expression_complementImpl implements PostfixExpressionComplementArgList
{
  /**
   * The cached value of the '{@link #getArgument_expression_list() <em>Argument expression list</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgument_expression_list()
   * @generated
   * @ordered
   */
  protected EList<argument_expression_list> argument_expression_list;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PostfixExpressionComplementArgListImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.POSTFIX_EXPRESSION_COMPLEMENT_ARG_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<argument_expression_list> getArgument_expression_list()
  {
    if (argument_expression_list == null)
    {
      argument_expression_list = new EObjectContainmentEList<argument_expression_list>(argument_expression_list.class, this, AnsicPackage.POSTFIX_EXPRESSION_COMPLEMENT_ARG_LIST__ARGUMENT_EXPRESSION_LIST);
    }
    return argument_expression_list;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AnsicPackage.POSTFIX_EXPRESSION_COMPLEMENT_ARG_LIST__ARGUMENT_EXPRESSION_LIST:
        return ((InternalEList<?>)getArgument_expression_list()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AnsicPackage.POSTFIX_EXPRESSION_COMPLEMENT_ARG_LIST__ARGUMENT_EXPRESSION_LIST:
        return getArgument_expression_list();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AnsicPackage.POSTFIX_EXPRESSION_COMPLEMENT_ARG_LIST__ARGUMENT_EXPRESSION_LIST:
        getArgument_expression_list().clear();
        getArgument_expression_list().addAll((Collection<? extends argument_expression_list>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.POSTFIX_EXPRESSION_COMPLEMENT_ARG_LIST__ARGUMENT_EXPRESSION_LIST:
        getArgument_expression_list().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.POSTFIX_EXPRESSION_COMPLEMENT_ARG_LIST__ARGUMENT_EXPRESSION_LIST:
        return argument_expression_list != null && !argument_expression_list.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //PostfixExpressionComplementArgListImpl
