/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.PostfixExpressionComplementDecrement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Postfix Expression Complement Decrement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PostfixExpressionComplementDecrementImpl extends postfix_expression_complementImpl implements PostfixExpressionComplementDecrement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PostfixExpressionComplementDecrementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.POSTFIX_EXPRESSION_COMPLEMENT_DECREMENT;
  }

} //PostfixExpressionComplementDecrementImpl
