/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.constant;
import org.xtext.example.ansic.expression;
import org.xtext.example.ansic.generic_selection;
import org.xtext.example.ansic.primary_expression;
import org.xtext.example.ansic.string_ufcg;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>primary expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.impl.primary_expressionImpl#getIdentifier <em>Identifier</em>}</li>
 *   <li>{@link org.xtext.example.ansic.impl.primary_expressionImpl#getConstant <em>Constant</em>}</li>
 *   <li>{@link org.xtext.example.ansic.impl.primary_expressionImpl#getString <em>String</em>}</li>
 *   <li>{@link org.xtext.example.ansic.impl.primary_expressionImpl#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.ansic.impl.primary_expressionImpl#getGeneric_selection <em>Generic selection</em>}</li>
 * </ul>
 *
 * @generated
 */
public class primary_expressionImpl extends MinimalEObjectImpl.Container implements primary_expression
{
  /**
   * The default value of the '{@link #getIdentifier() <em>Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdentifier()
   * @generated
   * @ordered
   */
  protected static final String IDENTIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIdentifier() <em>Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdentifier()
   * @generated
   * @ordered
   */
  protected String identifier = IDENTIFIER_EDEFAULT;

  /**
   * The cached value of the '{@link #getConstant() <em>Constant</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstant()
   * @generated
   * @ordered
   */
  protected constant constant;

  /**
   * The cached value of the '{@link #getString() <em>String</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected string_ufcg string;

  /**
   * The cached value of the '{@link #getExpression() <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpression()
   * @generated
   * @ordered
   */
  protected expression expression;

  /**
   * The cached value of the '{@link #getGeneric_selection() <em>Generic selection</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGeneric_selection()
   * @generated
   * @ordered
   */
  protected generic_selection generic_selection;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected primary_expressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.PRIMARY_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIdentifier()
  {
    return identifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIdentifier(String newIdentifier)
  {
    String oldIdentifier = identifier;
    identifier = newIdentifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.PRIMARY_EXPRESSION__IDENTIFIER, oldIdentifier, identifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public constant getConstant()
  {
    return constant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetConstant(constant newConstant, NotificationChain msgs)
  {
    constant oldConstant = constant;
    constant = newConstant;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsicPackage.PRIMARY_EXPRESSION__CONSTANT, oldConstant, newConstant);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setConstant(constant newConstant)
  {
    if (newConstant != constant)
    {
      NotificationChain msgs = null;
      if (constant != null)
        msgs = ((InternalEObject)constant).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.PRIMARY_EXPRESSION__CONSTANT, null, msgs);
      if (newConstant != null)
        msgs = ((InternalEObject)newConstant).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.PRIMARY_EXPRESSION__CONSTANT, null, msgs);
      msgs = basicSetConstant(newConstant, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.PRIMARY_EXPRESSION__CONSTANT, newConstant, newConstant));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public string_ufcg getString()
  {
    return string;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetString(string_ufcg newString, NotificationChain msgs)
  {
    string_ufcg oldString = string;
    string = newString;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsicPackage.PRIMARY_EXPRESSION__STRING, oldString, newString);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setString(string_ufcg newString)
  {
    if (newString != string)
    {
      NotificationChain msgs = null;
      if (string != null)
        msgs = ((InternalEObject)string).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.PRIMARY_EXPRESSION__STRING, null, msgs);
      if (newString != null)
        msgs = ((InternalEObject)newString).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.PRIMARY_EXPRESSION__STRING, null, msgs);
      msgs = basicSetString(newString, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.PRIMARY_EXPRESSION__STRING, newString, newString));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public expression getExpression()
  {
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpression(expression newExpression, NotificationChain msgs)
  {
    expression oldExpression = expression;
    expression = newExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsicPackage.PRIMARY_EXPRESSION__EXPRESSION, oldExpression, newExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpression(expression newExpression)
  {
    if (newExpression != expression)
    {
      NotificationChain msgs = null;
      if (expression != null)
        msgs = ((InternalEObject)expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.PRIMARY_EXPRESSION__EXPRESSION, null, msgs);
      if (newExpression != null)
        msgs = ((InternalEObject)newExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.PRIMARY_EXPRESSION__EXPRESSION, null, msgs);
      msgs = basicSetExpression(newExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.PRIMARY_EXPRESSION__EXPRESSION, newExpression, newExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public generic_selection getGeneric_selection()
  {
    return generic_selection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetGeneric_selection(generic_selection newGeneric_selection, NotificationChain msgs)
  {
    generic_selection oldGeneric_selection = generic_selection;
    generic_selection = newGeneric_selection;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsicPackage.PRIMARY_EXPRESSION__GENERIC_SELECTION, oldGeneric_selection, newGeneric_selection);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setGeneric_selection(generic_selection newGeneric_selection)
  {
    if (newGeneric_selection != generic_selection)
    {
      NotificationChain msgs = null;
      if (generic_selection != null)
        msgs = ((InternalEObject)generic_selection).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.PRIMARY_EXPRESSION__GENERIC_SELECTION, null, msgs);
      if (newGeneric_selection != null)
        msgs = ((InternalEObject)newGeneric_selection).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.PRIMARY_EXPRESSION__GENERIC_SELECTION, null, msgs);
      msgs = basicSetGeneric_selection(newGeneric_selection, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.PRIMARY_EXPRESSION__GENERIC_SELECTION, newGeneric_selection, newGeneric_selection));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AnsicPackage.PRIMARY_EXPRESSION__CONSTANT:
        return basicSetConstant(null, msgs);
      case AnsicPackage.PRIMARY_EXPRESSION__STRING:
        return basicSetString(null, msgs);
      case AnsicPackage.PRIMARY_EXPRESSION__EXPRESSION:
        return basicSetExpression(null, msgs);
      case AnsicPackage.PRIMARY_EXPRESSION__GENERIC_SELECTION:
        return basicSetGeneric_selection(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AnsicPackage.PRIMARY_EXPRESSION__IDENTIFIER:
        return getIdentifier();
      case AnsicPackage.PRIMARY_EXPRESSION__CONSTANT:
        return getConstant();
      case AnsicPackage.PRIMARY_EXPRESSION__STRING:
        return getString();
      case AnsicPackage.PRIMARY_EXPRESSION__EXPRESSION:
        return getExpression();
      case AnsicPackage.PRIMARY_EXPRESSION__GENERIC_SELECTION:
        return getGeneric_selection();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AnsicPackage.PRIMARY_EXPRESSION__IDENTIFIER:
        setIdentifier((String)newValue);
        return;
      case AnsicPackage.PRIMARY_EXPRESSION__CONSTANT:
        setConstant((constant)newValue);
        return;
      case AnsicPackage.PRIMARY_EXPRESSION__STRING:
        setString((string_ufcg)newValue);
        return;
      case AnsicPackage.PRIMARY_EXPRESSION__EXPRESSION:
        setExpression((expression)newValue);
        return;
      case AnsicPackage.PRIMARY_EXPRESSION__GENERIC_SELECTION:
        setGeneric_selection((generic_selection)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.PRIMARY_EXPRESSION__IDENTIFIER:
        setIdentifier(IDENTIFIER_EDEFAULT);
        return;
      case AnsicPackage.PRIMARY_EXPRESSION__CONSTANT:
        setConstant((constant)null);
        return;
      case AnsicPackage.PRIMARY_EXPRESSION__STRING:
        setString((string_ufcg)null);
        return;
      case AnsicPackage.PRIMARY_EXPRESSION__EXPRESSION:
        setExpression((expression)null);
        return;
      case AnsicPackage.PRIMARY_EXPRESSION__GENERIC_SELECTION:
        setGeneric_selection((generic_selection)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.PRIMARY_EXPRESSION__IDENTIFIER:
        return IDENTIFIER_EDEFAULT == null ? identifier != null : !IDENTIFIER_EDEFAULT.equals(identifier);
      case AnsicPackage.PRIMARY_EXPRESSION__CONSTANT:
        return constant != null;
      case AnsicPackage.PRIMARY_EXPRESSION__STRING:
        return string != null;
      case AnsicPackage.PRIMARY_EXPRESSION__EXPRESSION:
        return expression != null;
      case AnsicPackage.PRIMARY_EXPRESSION__GENERIC_SELECTION:
        return generic_selection != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (identifier: ");
    result.append(identifier);
    result.append(')');
    return result.toString();
  }

} //primary_expressionImpl
