/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.additive_expression;
import org.xtext.example.ansic.shift_expression_complement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>shift expression complement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.impl.shift_expression_complementImpl#getAdditive_expression <em>Additive expression</em>}</li>
 * </ul>
 *
 * @generated
 */
public class shift_expression_complementImpl extends MinimalEObjectImpl.Container implements shift_expression_complement
{
  /**
   * The cached value of the '{@link #getAdditive_expression() <em>Additive expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdditive_expression()
   * @generated
   * @ordered
   */
  protected additive_expression additive_expression;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected shift_expression_complementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.SHIFT_EXPRESSION_COMPLEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public additive_expression getAdditive_expression()
  {
    return additive_expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAdditive_expression(additive_expression newAdditive_expression, NotificationChain msgs)
  {
    additive_expression oldAdditive_expression = additive_expression;
    additive_expression = newAdditive_expression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsicPackage.SHIFT_EXPRESSION_COMPLEMENT__ADDITIVE_EXPRESSION, oldAdditive_expression, newAdditive_expression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAdditive_expression(additive_expression newAdditive_expression)
  {
    if (newAdditive_expression != additive_expression)
    {
      NotificationChain msgs = null;
      if (additive_expression != null)
        msgs = ((InternalEObject)additive_expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.SHIFT_EXPRESSION_COMPLEMENT__ADDITIVE_EXPRESSION, null, msgs);
      if (newAdditive_expression != null)
        msgs = ((InternalEObject)newAdditive_expression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.SHIFT_EXPRESSION_COMPLEMENT__ADDITIVE_EXPRESSION, null, msgs);
      msgs = basicSetAdditive_expression(newAdditive_expression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.SHIFT_EXPRESSION_COMPLEMENT__ADDITIVE_EXPRESSION, newAdditive_expression, newAdditive_expression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AnsicPackage.SHIFT_EXPRESSION_COMPLEMENT__ADDITIVE_EXPRESSION:
        return basicSetAdditive_expression(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AnsicPackage.SHIFT_EXPRESSION_COMPLEMENT__ADDITIVE_EXPRESSION:
        return getAdditive_expression();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AnsicPackage.SHIFT_EXPRESSION_COMPLEMENT__ADDITIVE_EXPRESSION:
        setAdditive_expression((additive_expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.SHIFT_EXPRESSION_COMPLEMENT__ADDITIVE_EXPRESSION:
        setAdditive_expression((additive_expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.SHIFT_EXPRESSION_COMPLEMENT__ADDITIVE_EXPRESSION:
        return additive_expression != null;
    }
    return super.eIsSet(featureID);
  }

} //shift_expression_complementImpl
