/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.struct_or_union_specifier_complement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>struct or union specifier complement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class struct_or_union_specifier_complementImpl extends MinimalEObjectImpl.Container implements struct_or_union_specifier_complement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected struct_or_union_specifier_complementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.STRUCT_OR_UNION_SPECIFIER_COMPLEMENT;
  }

} //struct_or_union_specifier_complementImpl
