/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.translation_unit_linha;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>translation unit linha</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class translation_unit_linhaImpl extends MinimalEObjectImpl.Container implements translation_unit_linha
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected translation_unit_linhaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.TRANSLATION_UNIT_LINHA;
  }

} //translation_unit_linhaImpl
