/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.ansic.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.ansic.AnsicPackage;
import org.xtext.example.ansic.atomic_type_specifier;
import org.xtext.example.ansic.enum_specifier;
import org.xtext.example.ansic.struct_or_union_specifier;
import org.xtext.example.ansic.type_specifier;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>type specifier</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ansic.impl.type_specifierImpl#getAtomic_type_specifier <em>Atomic type specifier</em>}</li>
 *   <li>{@link org.xtext.example.ansic.impl.type_specifierImpl#getStruct_or_union_specifier <em>Struct or union specifier</em>}</li>
 *   <li>{@link org.xtext.example.ansic.impl.type_specifierImpl#getEnum_specifier <em>Enum specifier</em>}</li>
 * </ul>
 *
 * @generated
 */
public class type_specifierImpl extends MinimalEObjectImpl.Container implements type_specifier
{
  /**
   * The cached value of the '{@link #getAtomic_type_specifier() <em>Atomic type specifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtomic_type_specifier()
   * @generated
   * @ordered
   */
  protected atomic_type_specifier atomic_type_specifier;

  /**
   * The cached value of the '{@link #getStruct_or_union_specifier() <em>Struct or union specifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStruct_or_union_specifier()
   * @generated
   * @ordered
   */
  protected struct_or_union_specifier struct_or_union_specifier;

  /**
   * The cached value of the '{@link #getEnum_specifier() <em>Enum specifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnum_specifier()
   * @generated
   * @ordered
   */
  protected enum_specifier enum_specifier;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected type_specifierImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsicPackage.Literals.TYPE_SPECIFIER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public atomic_type_specifier getAtomic_type_specifier()
  {
    return atomic_type_specifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAtomic_type_specifier(atomic_type_specifier newAtomic_type_specifier, NotificationChain msgs)
  {
    atomic_type_specifier oldAtomic_type_specifier = atomic_type_specifier;
    atomic_type_specifier = newAtomic_type_specifier;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsicPackage.TYPE_SPECIFIER__ATOMIC_TYPE_SPECIFIER, oldAtomic_type_specifier, newAtomic_type_specifier);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAtomic_type_specifier(atomic_type_specifier newAtomic_type_specifier)
  {
    if (newAtomic_type_specifier != atomic_type_specifier)
    {
      NotificationChain msgs = null;
      if (atomic_type_specifier != null)
        msgs = ((InternalEObject)atomic_type_specifier).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.TYPE_SPECIFIER__ATOMIC_TYPE_SPECIFIER, null, msgs);
      if (newAtomic_type_specifier != null)
        msgs = ((InternalEObject)newAtomic_type_specifier).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.TYPE_SPECIFIER__ATOMIC_TYPE_SPECIFIER, null, msgs);
      msgs = basicSetAtomic_type_specifier(newAtomic_type_specifier, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.TYPE_SPECIFIER__ATOMIC_TYPE_SPECIFIER, newAtomic_type_specifier, newAtomic_type_specifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public struct_or_union_specifier getStruct_or_union_specifier()
  {
    return struct_or_union_specifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStruct_or_union_specifier(struct_or_union_specifier newStruct_or_union_specifier, NotificationChain msgs)
  {
    struct_or_union_specifier oldStruct_or_union_specifier = struct_or_union_specifier;
    struct_or_union_specifier = newStruct_or_union_specifier;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsicPackage.TYPE_SPECIFIER__STRUCT_OR_UNION_SPECIFIER, oldStruct_or_union_specifier, newStruct_or_union_specifier);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStruct_or_union_specifier(struct_or_union_specifier newStruct_or_union_specifier)
  {
    if (newStruct_or_union_specifier != struct_or_union_specifier)
    {
      NotificationChain msgs = null;
      if (struct_or_union_specifier != null)
        msgs = ((InternalEObject)struct_or_union_specifier).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.TYPE_SPECIFIER__STRUCT_OR_UNION_SPECIFIER, null, msgs);
      if (newStruct_or_union_specifier != null)
        msgs = ((InternalEObject)newStruct_or_union_specifier).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.TYPE_SPECIFIER__STRUCT_OR_UNION_SPECIFIER, null, msgs);
      msgs = basicSetStruct_or_union_specifier(newStruct_or_union_specifier, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.TYPE_SPECIFIER__STRUCT_OR_UNION_SPECIFIER, newStruct_or_union_specifier, newStruct_or_union_specifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public enum_specifier getEnum_specifier()
  {
    return enum_specifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEnum_specifier(enum_specifier newEnum_specifier, NotificationChain msgs)
  {
    enum_specifier oldEnum_specifier = enum_specifier;
    enum_specifier = newEnum_specifier;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsicPackage.TYPE_SPECIFIER__ENUM_SPECIFIER, oldEnum_specifier, newEnum_specifier);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnum_specifier(enum_specifier newEnum_specifier)
  {
    if (newEnum_specifier != enum_specifier)
    {
      NotificationChain msgs = null;
      if (enum_specifier != null)
        msgs = ((InternalEObject)enum_specifier).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.TYPE_SPECIFIER__ENUM_SPECIFIER, null, msgs);
      if (newEnum_specifier != null)
        msgs = ((InternalEObject)newEnum_specifier).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsicPackage.TYPE_SPECIFIER__ENUM_SPECIFIER, null, msgs);
      msgs = basicSetEnum_specifier(newEnum_specifier, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsicPackage.TYPE_SPECIFIER__ENUM_SPECIFIER, newEnum_specifier, newEnum_specifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AnsicPackage.TYPE_SPECIFIER__ATOMIC_TYPE_SPECIFIER:
        return basicSetAtomic_type_specifier(null, msgs);
      case AnsicPackage.TYPE_SPECIFIER__STRUCT_OR_UNION_SPECIFIER:
        return basicSetStruct_or_union_specifier(null, msgs);
      case AnsicPackage.TYPE_SPECIFIER__ENUM_SPECIFIER:
        return basicSetEnum_specifier(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AnsicPackage.TYPE_SPECIFIER__ATOMIC_TYPE_SPECIFIER:
        return getAtomic_type_specifier();
      case AnsicPackage.TYPE_SPECIFIER__STRUCT_OR_UNION_SPECIFIER:
        return getStruct_or_union_specifier();
      case AnsicPackage.TYPE_SPECIFIER__ENUM_SPECIFIER:
        return getEnum_specifier();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AnsicPackage.TYPE_SPECIFIER__ATOMIC_TYPE_SPECIFIER:
        setAtomic_type_specifier((atomic_type_specifier)newValue);
        return;
      case AnsicPackage.TYPE_SPECIFIER__STRUCT_OR_UNION_SPECIFIER:
        setStruct_or_union_specifier((struct_or_union_specifier)newValue);
        return;
      case AnsicPackage.TYPE_SPECIFIER__ENUM_SPECIFIER:
        setEnum_specifier((enum_specifier)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.TYPE_SPECIFIER__ATOMIC_TYPE_SPECIFIER:
        setAtomic_type_specifier((atomic_type_specifier)null);
        return;
      case AnsicPackage.TYPE_SPECIFIER__STRUCT_OR_UNION_SPECIFIER:
        setStruct_or_union_specifier((struct_or_union_specifier)null);
        return;
      case AnsicPackage.TYPE_SPECIFIER__ENUM_SPECIFIER:
        setEnum_specifier((enum_specifier)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AnsicPackage.TYPE_SPECIFIER__ATOMIC_TYPE_SPECIFIER:
        return atomic_type_specifier != null;
      case AnsicPackage.TYPE_SPECIFIER__STRUCT_OR_UNION_SPECIFIER:
        return struct_or_union_specifier != null;
      case AnsicPackage.TYPE_SPECIFIER__ENUM_SPECIFIER:
        return enum_specifier != null;
    }
    return super.eIsSet(featureID);
  }

} //type_specifierImpl
