/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.parser.antlr.internal.InternalAnsicParser;
import org.xtext.example.services.AnsicGrammarAccess;

public class AnsicParser extends AbstractAntlrParser {

	@Inject
	private AnsicGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAnsicParser createParser(XtextTokenStream stream) {
		return new InternalAnsicParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DomainModel";
	}

	public AnsicGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AnsicGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
